### PR TITLE
[taskbar-grouping] added pinned items handling

### PR DESCRIPTION
**Pull request by ZimM-LostPolygon**
I use pinned items often, and having them always separated was somewhat annoying. The changes are aimed at keeping the pinned items grouped with the first instance of the app. Multiple processes of same app are also handled correctly. There are still some edge cases, though.

The overall idea is to keep track of the app window that's currently using the original unmodified AppId, which makes it grouped with the pin.

Pinned app not launched:
image

2 instances of pinned app launched:
image

### CODE REVIEW

**Comment by Nico04** [comment]
I'll love to see that published !

**Comment by m417z** [comment]
Thank you for the contribution. I just released a new version of the mod, which is also a full rewrite. One of the new options is for pinned items to be replaced with the first running instance (and not kept separated). The idea is similar to your implementation, but instead of keeping track of the state manually, the new code uses the relevant explorer functions.

**Comment by m417z** [comment]
@Nico04 added as an option in version 1.2 of the mod.

**Comment by Nico04** [comment]
Perfect thanks a lot !

**Pull request closed without merging**
